version: '3.8'

networks:
  web_network:
    driver: bridge

services:
  web-server:
    image: gudencio11/python-django:1.3.0
    ports: 
      - "8000:8000"
    restart: always
    networks:
      - web_network
    