# Generated by Django 4.2.3 on 2023-07-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_moedas', '0002_fotodeusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FotoDeUsuario',
            new_name='UserProfilePhoto',
        ),
    ]
