# Generated by Django 4.2.3 on 2023-07-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_moedas', '0003_rename_fotodeusuario_userprofilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
